# mobilenetv3_small-1-22121111211 -> resnext18-4-11221
net.conv1:
  t_layers: [null, tid_0=net.features.2.conv.3]
  modules: [null, RED]
  kwargs: [null, { cs: 64, alpha: 50.0 }]

net.layer2.0:
  t_layers: [tid_0=net.features.4.conv.3, tid_0=net.features.4.conv.3]
  modules: [RED, RED]
  kwargs: [{ cs: 64, alpha: 50.0 }, { cs: 128, alpha: 50.0 }]

net.layer3.0:
  t_layers: [tid_0=net.features.9.conv.3, tid_0=net.features.9.conv.3]
  modules: [RED, RED]
  kwargs: [{ cs: 128, alpha: 50.0 }, { cs: 256, alpha: 50.0 }]