EXPERIMENT:
  NAME: ""
  TAG: "rkd,resnet152=>mobilenetv2_aggressive_pool_x2"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "RKD"
  TEACHER: "ResNet152"
  STUDENT: "MobileNetV2_aggressive_pool_x2"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
RKD:
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 1.0
