EXPERIMENT:
  NAME: ""
  TAG: "student+,resnet152=>mobilenetv2_aggressive_pool_x2"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "ReED"
  TEACHER: "ResNet152"
  STUDENT: "MobileNetV2_aggressive_pool_x2"
  DIST_CONFIG: "configs/imagenet/mobilenetv2/student_x2+_dist_config.yaml"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "reed"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
