model.0:
  t_layers: [ null, tid_0=maxpool ]
  modules: [ null, RED ]
  kwargs: [ null, { cs: 32, distance: cosine, alpha: 0 } ]

model.2:
  t_layers: [ tid_0=layer2.0, tid_0=layer2.0 ]
  modules: [ RED, RED ]
  kwargs: [ { cs: 64, distance: cosine, alpha: 0 }, { cs: 128, distance: cosine, alpha: 0 } ]

model.4:
  t_layers: [ tid_0=layer3.0, tid_0=layer3.0 ]
  modules: [ RED, RED ]
  kwargs: [ { cs: 128, distance: cosine, alpha: 0 }, { cs: 256, distance: cosine, alpha: 0 } ]

model.6:
  t_layers: [ tid_0=layer4.0, tid_0=layer4.0 ]
  modules: [ RED, RED ]
  kwargs: [ { cs: 256, distance: cosine, alpha: 0 }, { cs: 512, distance: cosine, alpha: 0 } ]