EXPERIMENT:
  NAME: ""
  TAG: "fitnet,resnet18=>resnet18_aggressive_pool"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "FITNET"
  TEACHER: "ResNet18"
  STUDENT: "ResNet18_aggressive_pool"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
FITNET:
  HINT_LAYER: 4
  INPUT_SIZE: (224, 224)
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 5.0
