EXPERIMENT:
  NAME: ""
  TAG: "kd,resnet18=>resnet18_aggressive_pool"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet18"
  STUDENT: "ResNet18_aggressive_pool"
SOLVER:
  BATCH_SIZE: 512
#  EPOCHS: 100
#  LR: 0.2
#  LR_DECAY_STAGES: [30, 60, 90]
  EPOCHS: 300
  LR: 0.002
  LR_DECAY_STAGES: [180, 240, 270]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
KD:
  TEMPERATURE: 1
  LOSS:
    CE_WEIGHT: 0.5
    KD_WEIGHT: 0.5
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
