EXPERIMENT:
  NAME: ""
  TAG: "reed+kd,resnet18=>resnet18_aggressive_pool"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "ReED"
  TEACHER: "ResNet18"
  STUDENT: "ResNet18_aggressive_pool"
  DIST_CONFIG: "configs/imagenet/resnet18/reed+kd_dist_config.yaml"
SOLVER:
  BATCH_SIZE: 512
#  EPOCHS: 100
#  LR: 0.2
#  LR_DECAY_STAGES: [30, 60, 90]
  EPOCHS: 300
  LR: 0.2
  LR_DECAY_STAGES: [ 30, 90, 180, 240, 270 ]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "reed"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
