conv1:
  t_layers: [ null, tid_0=layer2.0 ]
  modules: [ null, RED ]
  kwargs: [ null, { cs: 64, distance: cosine, alpha: 1. } ]

layer2.0:
  t_layers: [ tid_0=layer3.0, tid_0=layer3.0 ]
  modules: [ RED, RED ]
  kwargs: [ { cs: 64, distance: cosine, alpha: 1. }, { cs: 128, distance: cosine, alpha: 1. } ]

layer3.0:
  t_layers: [ tid_0=layer4.0, tid_0=layer4.0 ]
  modules: [ RED, RED ]
  kwargs: [ { cs: 128, distance: cosine, alpha: 1. }, { cs: 256, distance: cosine, alpha: 1. } ]