net.features.0:
  t_layers: [null, tid_0=features.4.conv.1]
  modules: [null, RED]
  kwargs: [null, { cs: 32 }]

net.features.2.conv.3:
  t_layers: [tid_0=features.7.conv.1, tid_0=features.7.conv.1]
  modules: [RED, RED]
  kwargs: [{ cs: 96 }, { cs: 96 }]

net.features.4.conv.3:
  t_layers: [tid_0=features.14.conv.1, tid_0=features.14.conv.1]
  modules: [RED, RED]
  kwargs: [{ cs: 144 }, { cs: 144 }]

net.classifier:
  t_layers: [ null, tid_0=classifier]
  modules: [ null, KD ]
  kwargs: [ null, {  } ]
