head:
  t_layers: [null, tid_0=downblocks.2]
  modules: [ null, RED ]
  kwargs: [ null, { cs: 128, distance: cosine, alpha: 1. } ]

downblocks.2:
  t_layers: [tid_0=downblocks.5, tid_0=downblocks.5]
  modules: [ RED, RED ]
  kwargs: [ { cs: 128, distance: cosine, alpha: 1. }, { cs: 128, distance: cosine, alpha: 1. } ]

downblocks.5:
  t_layers: [tid_0=downblocks.8, tid_0=downblocks.8]
  modules: [ RED, RED ]
  kwargs: [ { cs: 256, distance: cosine, alpha: 1. }, { cs: 256, distance: cosine, alpha: 1. } ]

upblocks.7:
  t_layers: [tid_0=upblocks.3, tid_0=upblocks.3]
  modules: [ RED, RED ]
  kwargs: [ { cs: 256, distance: cosine, alpha: 1. }, { cs: 256, distance: cosine, alpha: 1. } ]

upblocks.11:
  t_layers: [tid_0=upblocks.7, tid_0=upblocks.7]
  modules: [ RED, RED ]
  kwargs: [ { cs: 256, distance: cosine, alpha: 1. }, { cs: 256, distance: cosine, alpha: 1. } ]

tail:
  t_layers: [ tid_0=upblocks.11, null ]
  modules: [ RED, null ]
  kwargs: [ { cs: 128, distance: cosine, alpha: 1. }, null ]

